import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import "./globals.css";

import { Dev } from "@/components/dev";

export const metadata: Metadata = {
  title: "Nexara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Dev />
        <ThemeProvider attribute="data-theme">{children}</ThemeProvider>
      </body>
    </html>
  );
}
