import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import { Dev } from "@/components/dev";
import "./globals.css";
import localFont from "next/font/local";

import { cn } from "@/lib/utils";

const fontMontserrat = localFont({
  src: "../assets/fonts/Montserrat-Variable.ttf",
});

export const metadata: Metadata = {
  title: "Nexara",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={cn("antialiased", fontMontserrat.className)}>
        <NextIntlClientProvider>
          <Analytics />
          <Dev />
          <ThemeProvider attribute="data-theme" defaultTheme="dark">
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
